# Generated by Django 2.0.5 on 2018-05-08 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.PositiveIntegerField(unique=True)),
                ('source', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\d{10,11}$')])),
                ('destination', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\d{10,11}$')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callcontrol.PhoneCall')),
            ],
        ),
    ]
