# Generated by Django 2.0.5 on 2018-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_start', models.TimeField()),
                ('period_end', models.TimeField()),
                ('standing_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
