# Generated by Django 2.0.5 on 2018-05-11 20:48

from django.db import migrations


def create_initial_prices(apps, schema_editor):
    """
    Create initial 'standard' and 'reduced' prices.
    """
    Pricing = apps.get_model('callcontrol', 'Pricing')

    Pricing.objects.create(
        name='standard',
        period_start='06:00',
        period_end='22:00',
        standing_price=0.36,
        price_per_minute=0.09
    )
    Pricing.objects.create(
        name='reduced',
        period_start='22:00',
        period_end='06:00',
        standing_price=0.36,
        price_per_minute=0.00
    )


class Migration(migrations.Migration):

    dependencies = [
        ('callcontrol', '0002_pricing'),
    ]

    operations = [
        migrations.RunPython(create_initial_prices),
    ]
