# Generated by Django 2.0.5 on 2018-05-12 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcontrol', '0003_pricing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='destination',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='source',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\d{10,11}$')]),
        ),
    ]
