# Generated by Django 2.0.5 on 2018-05-14 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcontrol', '0004_auto_20180511_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCallParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination')], max_length=11)),
                ('phone_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\d{10,11}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='phonecall',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='phonecall',
            name='source',
        ),
        migrations.AddField(
            model_name='phonecallparticipant',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callcontrol.PhoneCall'),
        ),
    ]
